# Generated by Django 5.1.5 on 2025-01-21 03:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default='Sample Question', max_length=255)),
                ('option_1', models.CharField(default='Option 1', max_length=100)),
                ('option_2', models.CharField(default='Option 2', max_length=100)),
                ('option_3', models.CharField(default='Option 3', max_length=100)),
                ('option_4', models.CharField(default='Option 4', max_length=100)),
                ('correct_option', models.CharField(default='Option 1', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MockTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('questions_answered', models.ManyToManyField(blank=True, to='apis.question')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_answer', models.CharField(default='Option 1', max_length=100)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('mock_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.mocktest')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.question')),
            ],
        ),
    ]
