# Generated by Django 5.1.5 on 2025-01-21 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mocktest',
            name='name',
        ),
        migrations.RemoveField(
            model_name='question',
            name='answer',
        ),
        migrations.AddField(
            model_name='mocktest',
            name='title',
            field=models.CharField(default='Untitled Mock Test', max_length=256),
        ),
        migrations.AddField(
            model_name='question',
            name='correct_answer',
            field=models.CharField(default='Untitled', max_length=128),
        ),
        migrations.AddField(
            model_name='question',
            name='options',
            field=models.JSONField(default=None),
        ),
        migrations.AlterField(
            model_name='mocktest',
            name='questions',
            field=models.ManyToManyField(default='Untitled Mock Test', to='apis.question'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.CharField(max_length=512),
        ),
    ]
